server:
  port: '8083'
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:mem:bookShopClientsDb'
    driverClassName: org.h2.Driver
    username: sa
    schema: 'classpath:db/schema.sql'
    data: 'classpath:db/data.sql'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher