package KieRule;
import lv.alija.bookShopMicro2.model.Client;

rule "Senior"

when
clientObject: Client(type == type.SENIOR && age > 64 || documentForDiscount == true);
then
clientObject.setDiscount(20L);
end;

rule "Student"

when
clientObject: Client(type == type.STUDENT && age < 64 && documentForDiscount==true);
then
clientObject.setDiscount(15L);
end;

rule "Scholar"

when
clientObject: Client(type == type.SCHOLAR && age < 20 && documentForDiscount==true);
then
clientObject.setDiscount(10L);
end;

rule "Person"

when
clientObject: Client(type == type.PERSON && documentForDiscount==true);
then
clientObject.setDiscount(5L);
end;

rule "Any"
when
clientObject: Client(type == type.ANY && documentForDiscount==false);
then
clientObject.setDiscount(0L);
end;